org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.java.home=C:\\PROGRA~1\\MIE74D~1\\jdk-21.0.12.8-hotspot
android.user.home=C:\\Users\\NESTOR~1\\.android
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
android.disallowKotlinSourceSets=false
android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableAppCompileTimeRClass=false
android.usesSdkInManifest.disallowed=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
android.builtInKotlin=false
android.newDsl=false
